project:
  type: website

website:
  title: "Classifier Calibration"
  sidebar:
    style: "docked"
    search: true
    logo: "./assets/images/clacal.png"
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Home
      - href: ecml-pkdd-2020-tutorial/index.qmd
        text: ECML-PKDD 2020 Tutorial
      - href: survey/index.qmd
        text: ML survey
      - href: videos/index.qmd
        text: Videos
  page-footer:
    left: |
      Classifier Calibration by Miquel Perello Nieto and Peter Flach.
    right: |
      This website was built with <a href="https://quarto.org/">Quarto</a>.

format:
  html:
    theme: journal
    css: styles.css
    toc: true
